# Generated by Django 3.2.4 on 2021-06-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(to='STORE.Images'),
        ),
    ]
