# Generated by Django 3.2.4 on 2021-06-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0002_auto_20210627_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='STORE.category'),
        ),
    ]
