# Generated by Django 3.2.4 on 2021-09-03 18:43

import STORE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0003_auto_20210903_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, max_length=300, upload_to=STORE.models.image_upload),
        ),
    ]
