# Generated by Django 3.2.4 on 2021-07-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0003_alter_address_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
