# Generated by Django 3.2.4 on 2021-06-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0003_alter_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, to='STORE.Images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='STORE.Size'),
        ),
    ]
