# Generated by Django 3.2.4 on 2021-07-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0004_alter_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
