# Generated by Django 3.2.4 on 2021-06-27 14:28

import STORE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0004_auto_20210627_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='images/preloader.png', upload_to=STORE.models.image_upload),
        ),
    ]
