# Generated by Django 3.2.4 on 2021-09-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0004_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
