# Generated by Django 3.2.4 on 2021-07-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0005_alter_product_discount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
