# Generated by Django 3.2.4 on 2021-06-27 17:52

import STORE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0006_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=STORE.models.image_upload),
        ),
    ]
