# Generated by Django 3.2.4 on 2021-06-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0007_auto_20210627_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='child',
            field=models.CharField(default='sad', max_length=100),
            preserve_default=False,
        ),
    ]
