# Generated by Django 3.2.4 on 2021-07-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='numbers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='STORE.coupon'),
        ),
    ]
