# Generated by Django 3.2.4 on 2021-06-27 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0009_auto_20210627_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='product_image',
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='STORE.product'),
        ),
    ]
