# Generated by Django 3.2.4 on 2021-06-27 21:04

import STORE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0010_auto_20210627_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to=STORE.models.image_upload),
        ),
    ]
