# Generated by Django 3.2.4 on 2021-07-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0010_coupon_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
