# Generated by Django 3.2.4 on 2021-06-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0011_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
    ]
