# Generated by Django 3.2.4 on 2021-08-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0012_alter_manufacturer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_cart',
            name='cart_id',
        ),
    ]
