# Generated by Django 3.2.4 on 2021-06-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0013_auto_20210628_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_product', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='STORE.product')),
            ],
        ),
    ]
