# Generated by Django 3.2.4 on 2021-06-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0014_auto_20210628_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='my_image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
