# Generated by Django 3.2.4 on 2021-06-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0015_product_my_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='my_image_url',
        ),
    ]
