# Generated by Django 3.2.4 on 2021-07-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0017_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='device',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
