# Generated by Django 3.2.4 on 2021-08-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0017_auto_20210803_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
