# Generated by Django 3.2.4 on 2021-08-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20210724_1410'),
        ('STORE', '0018_shipping_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region'),
        ),
    ]
