# Generated by Django 3.2.4 on 2021-07-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0018_filter_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_shiiping',
            field=models.BooleanField(default=False),
        ),
    ]
