# Generated by Django 3.2.4 on 2021-07-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0019_product_free_shiiping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='free_shiiping',
            new_name='free_shipping',
        ),
    ]
