# Generated by Django 3.2.4 on 2021-07-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0020_rename_free_shiiping_product_free_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='price_1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='filter',
            name='price_2',
            field=models.PositiveIntegerField(),
        ),
    ]
