# Generated by Django 3.2.4 on 2021-07-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0021_auto_20210702_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='price_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='price_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
