# Generated by Django 3.2.4 on 2021-08-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0021_alter_order_statue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='egy_currency',
            field=models.IntegerField(default=0),
        ),
    ]
