# Generated by Django 3.2.4 on 2021-08-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0023_auto_20210821_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-modified_date',)},
        ),
        migrations.AddField(
            model_name='wishlist',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
