# Generated by Django 3.2.4 on 2021-08-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0025_blog_comments_blog_images_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_images',
            name='user',
        ),
    ]
