# Generated by Django 3.2.4 on 2021-07-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0025_alter_filter_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='price_1',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='price_2',
            field=models.PositiveIntegerField(blank=True, default=200, null=True),
        ),
    ]
