# Generated by Django 3.2.4 on 2021-08-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0027_auto_20210823_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='product',
        ),
        migrations.AddField(
            model_name='deals',
            name='product',
            field=models.ManyToManyField(to='STORE.Product'),
        ),
    ]
