# Generated by Django 3.2.4 on 2021-08-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0028_auto_20210823_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='product',
        ),
        migrations.AddField(
            model_name='deals',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='STORE.product'),
            preserve_default=False,
        ),
    ]
