# Generated by Django 3.2.4 on 2021-07-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0029_cart_product_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_cart',
            old_name='product',
            new_name='products',
        ),
    ]
