# Generated by Django 3.2.4 on 2021-08-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0029_auto_20210823_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='details',
        ),
    ]
