# Generated by Django 3.2.4 on 2021-07-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0030_rename_product_product_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
