# Generated by Django 3.2.4 on 2021-08-25 17:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0031_blogs_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
