# Generated by Django 3.2.4 on 2021-07-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0031_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
    ]
