# Generated by Django 3.2.4 on 2021-07-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0032_remove_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_cart',
            name='product_id',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
