# Generated by Django 3.2.4 on 2021-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0033_auto_20210825_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='comments',
            field=models.ManyToManyField(blank=True, to='STORE.Blog_Comments'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ManyToManyField(blank=True, to='STORE.Blog_Images'),
        ),
    ]
